package ETC;

public class Ex01_Exception {
	public static void main(String[] args) {
		System.out.println("0으로 나눔니다.");
		// 연산 문제가 발생해도 일단 프로그램이 강제로 종료되지 않는다.
		try {
		System.out.println(0/0);
		
	} catch(Exception e) {
		e.printStackTrace();
		System.out.println(e.getMessage());
	} finally {
		System.out.println("무조건 실행하는 코드");
		}
	}
}
